### ISSUE TITLE
To support Stable diffusion 2.0

### ISSUE THREAD

**Issue by zhangpzh** [cross-domain-compositing/cross-domain-compositing#10]
I personally admire your work very much. Useful. Since SD 2 has already come. Have you ever thought of changing the backend of the CDC inpainting framework from SD 1.4 to SD 2.0 ? Sincerely.

**Comment by roy-hachnochi** [comment]
Thank you for your support. We are currently not planning to integrate our work to SD 2.0. We would however be glad to assist anyone who would like to work on this.
