### ISSUE TITLE
What is the VRAM Requirement for this?

### ISSUE THREAD

**Issue by Njasa2k** [cross-domain-compositing/cross-domain-compositing#2]
What is the VRAM Requirement for this? Can it be run on consumer hardware?

**Comment by cross-domain-compositing** [comment]
In our experiments we use Nvidia GeForce RTX 2080 Ti with 11GB memory and it is sufficient for a 1-image batch. If available, we recommend using a higher-memory GPU to run multiple images, since our method usually requires creating a grid to find the best parameter configuration.
