### ISSUE TITLE
How the object immersion is reproduced？

### ISSUE THREAD

**Issue by zyshawn** [cross-domain-compositing/cross-domain-compositing#4]
Hello author, thank you very much for the open source, I'm just getting into this direction, may I ask how the Object immersion is reproduced in the paper? I see that the readme doesn't mention it.

**Comment by VongolaWu** [comment]
Hi author, I also have this question. How can we use your code for object immersion?

**Comment by pribadihcr** [comment]
+1

**Comment by cross-domain-compositing** [comment]
Thanks for the replies. Please refer to [this link](https://drive.google.com/drive/folders/1tgm4nG_SnUlo7dHCuvwRWKzJDqNiaSN0?usp=sharing) for data examples (including input images and masks for both immersion and scribble tasks). As for reproducing the results, please see the Usage section in the readme, and refer to the paper for parameters configuration. For object immersion, the results from the paper are reproduced with:
`T_in = 0.5`
`down_N_in = 2`
`repaint_start = 0.2`
