### ISSUE TITLE
detailed instruction to run "Object Immersion in Paintings"

### ISSUE THREAD

**Issue by Youngon** [cross-domain-compositing/cross-domain-compositing#5]
Could you please share some detail instructions for running "Object Immersion in Paintings" task?

**Comment by cross-domain-compositing** [comment]
Instructions are given in the readme (see [Data](https://github.com/cross-domain-compositing/cross-domain-compositing/blob/4ee164b3f3855afed496beb1c634e44a32727ae1/README.md?plain=1#L140) and [Examples](https://github.com/cross-domain-compositing/cross-domain-compositing/blob/4ee164b3f3855afed496beb1c634e44a32727ae1/README.md?plain=1#L78)).
In short - you simply need to download the data from the supplied link, and change the command to match your data path and parameter preferences. To recreate our Object Immersion results, use `--T_in 0.5 --T_out 1 --N_in 2 --N_out 1 --repaint_start 0.2` as the CL parameters.
