### ISSUE TITLE
sampling_conf.strength is none

### ISSUE THREAD

**Issue by Git-oNmE** [cross-domain-compositing/cross-domain-compositing#6]
Hello, when I try to reproduce the object immersion, I come into this error.
![image](https://github.com/cross-domain-compositing/cross-domain-compositing/assets/29742421/98246abe-4928-41a2-9054-695833dfd7ac)

Here is my command:
```
#!/bin/bash

export PYTHONPATH=$(pwd):$(pwd)/ResizeRight

# --from_file examples/immersion/prompts.txt \

python scripts_cdc/img2img_inpaint.py \
	--config configs/stable-diffusion/v1-inpainting-inference.yaml \
	--ckpt models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt \
	--prompt "A white toaster is on the dining table, which is filled with food." \
	--init_img examples/immersion/images-2/ \
	--mask examples/immersion/masks-2/ \
	--n_samples 1 \
	--outdir outputs/immersion-2 \
	--ddim_steps 50 \
	--strength_in 1 \
	--strength_out 0 \
	--T_in 0.5 \
	--T_out 1 \
	--down_N_in 2 \
	--down_N_out 1 \
	--blend_pix 0 \
	--seed 1234 \
	--repaint_start 0.2
```
Could you help me to fix this? Thanks!  :)

**Comment by Git-oNmE** [comment]
I finally fix this by manually set the sampling_conf.strength value to 1 in the code.
![image](https://github.com/cross-domain-compositing/cross-domain-compositing/assets/29742421/5e6ad838-06d0-444e-8521-88c7c82fff42)

**Comment by cross-domain-compositing** [comment]
Thanks for the notice. Pushed commit cb70100 to fix this issue, will hopefully work now.
Note that you should use `strength_in` and `strength_out` , which enable noising masked and unmasked regions to different levels.
Also note that to reproduce the immersion results, you should use `img2img.py`, and not `img2img_inpaint.py`.
