### ISSUE TITLE
img2img.py: error: ambiguous option: --strength could match --strength_in, --strength_out

### ISSUE THREAD

**Issue by zhangpzh** [cross-domain-compositing/cross-domain-compositing#8]
As described in the title. When I try to run the demo script in the README, I encounter this error.

**Comment by roy-hachnochi** [comment]
This part of the README is apparantly outdated, thanks for bringing this to our attention. Please use `strength_in` and `strength_out` (for separate noising levels for inner and outer regions accordingly), or just erase the flag if you wish to use the default. We'll fix this in the README instructions.
