### ISSUE TITLE
Synthesize the product image into the background image

### ISSUE THREAD

**Issue by goozi** [cross-domain-compositing/cross-domain-compositing#9]
Thank you very much for your work, it really solved my big problem! Now I have a business scene that is like this. I need to synthesize my product image (which needs to be cut out from a large picture with mask, such as a microwave oven) into another background picture (which also needs to be cut out from a large picture with mask, such as a kitchen). I think that the SCRIBBLE or BACKGROUND AUGMENTATION  is close to this scene. But what should I write on the command line? I am stuck, please help me, provide a command line sample! Thank you very much!

**Comment by roy-hachnochi** [comment]
From what I understand, the task you are describing is image blending - stitching a foregroung image on top of a new background.   An example of a (FG, BG) pair would better help to understand your goal, but I would recommend to manually create a comopsite image by naive copy-paste, and create a mask which edits only a boundary around the FG object. Then, simply use the command in the README, and play a bit with 
`--T_in, --down_N_in, --repaint_start`, probably starting with (0.4, 1, 0.2) accordingly.  
Note that our focus is on *cross-domain* editing, which is not the case with your example, but it is possible for it to still work.
